name: Pull Request Flow
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  client-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - run: cd frontend && npm install && npm test
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"
      - run: go test ./...
